import type { Metadata } from 'next';
import { Geist_Mono, Montserrat } from 'next/font/google';
import './globals.css';
import { AuthProvider } from './providers/AuthProvider';

const sans = Montserrat({
	variable: '--font-inter',
	weight: ['400', '600'],
});

const mono = Geist_Mono({
	variable: '--font-geist-mono',
	weight: ['400', '600'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<AuthProvider>
			<html lang="en">
				<body
					className={`${sans.variable} ${mono.variable} antialiased h-dvh bg-gradient-to-r from-slate-500 to-slate-800`}
				>
					<main className="h-dvh flex flex-col">{children}</main>
				</body>
			</html>
		</AuthProvider>
	);
}
